{
 "title": "Speedtest",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "networks",
    "label": "Networks:",
    "query": {
     "query": "label_values(internet_server_latency,network)"
    }
   },
   {
    "name": "servers",
    "label": "Servers:",
    "query": {
     "query": "label_values(internet_server_latency,server)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Internet Download Speed by Server",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "internet_download_speed{network=~\"${networks}\", server=~\"${servers}\"}",
     "legendFormat": "({{network}}) - {{server}}"
    }
   ]
  },
  {
   "title": "Internet Upload Speed by Server",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "internet_upload_speed{network=~\"${networks}\", server=~\"${servers}\"}",
     "legendFormat": "({{network}}) - {{server}}"
    }
   ]
  },
  {
   "title": "Internet Server Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "internet_server_latency{network=~\"${networks}\", server=~\"${servers}\"}",
     "legendFormat": "({{network}}) - {{server}}"
    }
   ]
  }
 ]
}