class Paths:

    BASH_INTERPRETER_FILE = "/usr/bin/sh"

    PYTHON_INTERPRETER_FILE = ".venv/bin/python3.11"

    PROJECT_DIRECTORY = "/scripts/speedtest"

    ASSETS_DIRECTORY = f"{PROJECT_DIRECTORY}/assets"

    TEMPLATES_DIRECTORY = f"{ASSETS_DIRECTORY}/templates"

    ERRORS_DIRECTORY = f"{PROJECT_DIRECTORY}/errors"

    LOGS_DIRECTORY = f"{PROJECT_DIRECTORY}/logs"

    ENVIRONMENT_FILE = f"{PROJECT_DIRECTORY}/.env"
