# Global configuration
global:
  scrape_interval: 15s # How often to scrape metrics (default is 1m)
  evaluation_interval: 15s # How often to evaluate rules (default is 1m)

# A scrape configuration containing endpoints to scrape.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:{PORT}']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:{NODE_PORT}']

  - job_name: 'metrics'
    static_configs:
      - targets: ['localhost:{METRICS_PORT}']